config/routes.rb
AccountSubdomain::Engine.routes.draw do
  resources :accounts, :except => [:edit, :update]
  root to: 'accounts#new'
end

app/models/account_subdomain/account.rb
module AccountSubdomain
  class Account < ActiveRecord::Base
    validates :subdomain, :presence => true, uniqueness: {message: 'already been taken.'}, :length => {:within => 2..50}
    AccountSubdomain.reflections.each do|reflection|
      self.class_eval "#{reflection}"
    end
  end
end

app/controllers/account_subdomain/accounts_controller.rb
#require_dependency "account_subdomain/application_controller"

module AccountSubdomain
  class AccountsController < ApplicationController
    before_action :set_account, only: [:show, :destroy]

    # GET /accounts
    def index
      @accounts = AccountSubdomain::Account.all
    end

    # GET /accounts/1
    def show
    end

    # GET /accounts/new
    def new
      @account = AccountSubdomain::Account.new
    end

    # POST /accounts
    def create
      @account = AccountSubdomain::Account.new(account_params)

      if @account.save
        redirect_to eval("#{AccountSubdomain.after_creation_url}(:subdomain => '#{@account.subdomain}')"), notice: 'Account was successfully created.'
      else
        render action: 'new'
      end
    end

    # DELETE /accounts/1
    def destroy
      @account.destroy
      redirect_to accounts_url, notice: 'Account was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_account
        @account = AccountSubdomain::Account.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def account_params
        params.require(:account).permit(:subdomain)
      end
  end
end

app/controllers/account_subdomain/application_controller.rb
class AccountSubdomain::ApplicationController < ApplicationController
  AccountSubdomain.action_controller_filters.each_pair do|key, reflection|
    reflection.each do|_rel|
      self.class_eval "#{key} :#{_rel.to_sym}"
    end
  end
end

app/helpers/account_subdomain/accounts_helper.rb
module AccountSubdomain
  module AccountsHelper

    def subdomain
      request.subdomain(AccountSubdomain.tld_length)
    end

    def validate_subdomain
      redirect_to eval("#{AccountSubdomain.redirect_path}"), :error => 'You are not authorized.' unless current_subdomain.present?
    end

    def current_subdomain
      @subdomain ||= AccountSubdomain::Account.find_by_subdomain(subdomain)
    end

  end
end

app/helpers/account_subdomain/application_helper.rb
module AccountSubdomain
  module ApplicationHelper
  end
end

app/helpers/account_subdomain/url_helper.rb
module AccountSubdomain
  module UrlHelper
    def with_subdomain(subdomain)
      subdomain = (subdomain || "")
      subdomain += '.' unless subdomain.empty?
      [subdomain, request.domain(AccountSubdomain.tld_length), request.port_string].join
    end

    def url_for(options = nil)
      if options.kind_of?(Hash) && options.has_key?(:subdomain)
        options[:host] = with_subdomain(options.delete(:subdomain))
      end
      super
    end
  end
end

app/views/account_subdomain/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subdomain %><br>
    <%= f.text_field :subdomain %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/account_subdomain/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <thead>
    <tr>
      <% (AccountSubdomain::Account.column_names - ['id', 'created_at', 'updated_at']).each do|column_name|%>
      <th><%= column_name.humanize.capitalize%></th>
      <%end%>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <% (AccountSubdomain::Account.column_names - ['id', 'created_at', 'updated_at']).each do|column_name|%>
          <td><%= account.send(column_name) %></td>
        <%end%>

        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Destroy', account, :method => :delete, :data => { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/account_subdomain/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/account_subdomain/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subdomain:</strong>
  <%= @account.subdomain %>
</p>

<%= link_to 'Back', accounts_path %>

app/views/layouts/account_subdomain/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AccountSubdomain</title>
  <%= stylesheet_link_tag    "account_subdomain/application", media: "all" %>
  <%= javascript_include_tag "account_subdomain/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>